site_name: DAOstack Developer Portal
version: v2.0
repo_url: https://github.com/dOrgTech/DAOstack-Hackers-Kit/
repo_name: dOrgTech/DAOstack-Hackers-Kit
site_description: A platform for building DAOs

theme:
  name: readthedocs
  logo: 'images/daostack-logoW.svg'

nav:
- Home: 'index.md'
- Arc 2.0: 'arc2-overview.md'
- Stack:
  - Infra:
    - Intro: 'stack/infra/intro.md'
    - Holographic Consensus: 'stack/infra/holographic-consensus.md'
  - Arc: 'stack/arc.md'
  - Subgraph:
    - Intro: 'stack/subgraph/intro.md'
    - GraphQL queries: 'stack/subgraph/queries.md'
    - Entities: 'stack/subgraph/entities.md'
  - Arc.js:
    - Intro: 'stack/arcjs/intro.md'
    - Getting Started: 'stack/arcjs/intro.md'
    - How To Use: 'stack/arcjs/intro.md'
    - Query, Observables & Subscriptions: 'stack/arcjs/intro.md'
    - Quick Example: 'stack/arcjs/intro.md'
  - Alchemy: 'stack/alchemy.md'
- Plugins:
  - NFT Manager: 'plugins/nft-manager.md'
  - Funding Request: 'plugins/funding-request.md'
  - Token Trade: 'plugins/token-trade.md'
- Tutorials:
  - Create your own DAO: 'tutorials/create-a-dao.md'
  - Arc.react:  'tutorials/arc-react.md'
  - Register a generic plugin: 'tutorials/generic-plugin.md'
  - Register a plugin in the stack:
    - Intro: 'tutorials/register-a-plugin/intro.md'
    - Arc: 'tutorials/register-a-plugin/arc.md'
    - Subgraph: 'tutorials/register-a-plugin/subgraph.md'
    - Migration: 'tutorials/register-a-plugin/migration.md'
    - Test environment: 'tutorials/register-a-plugin/test-environment.md'
    - Arc.js: 'tutorials/register-a-plugin/arcjs.md'
    - Alchemy: 'tutorials/register-a-plugin/alchemy.md'